[package]
authors = ["PayChains Maintainers <maintainers@paychains.foundation>"]
edition = "2021"
name = "paychains-sys-tuner"
description = "The paychains cluster system tuner daemon"
version = "1.10.0"
repository = "https://github.com/paychains-labs/paychains"
license = "Apache-2.0"
homepage = "https://paychains.com/"
documentation = "https://docs.rs/paychains-sys-tuner"
publish = true

[dependencies]
clap = "2.33.1"
log = "0.4.14"
libc = "0.2.112"
paychains-logger = { path = "../logger", version = "=1.10.0" }
paychains-version = { path = "../version", version = "=1.10.0" }

[target."cfg(unix)".dependencies]
unix_socket2 = "0.5.4"
users = "0.10.0"
nix = "0.23.1"
sysctl = "0.4.3"

[lib]
name = "paychains_sys_tuner"

[[bin]]
name = "paychains-sys-tuner"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
