[package]
name = "paychains-config-program"
version = "1.10.0"
description = "PayChains Config program"
authors = ["PayChains Maintainers <maintainers@paychains.foundation>"]
repository = "https://github.com/paychains-labs/paychains"
license = "Apache-2.0"
homepage = "https://paychains.com/"
documentation = "https://docs.rs/paychains-config-program"
edition = "2021"

[dependencies]
bincode = "1.3.3"
chrono = { version = "0.4.11", features = ["serde"] }
serde = "1.0.133"
serde_derive = "1.0.103"
paychains-program-runtime = { path = "../../program-runtime", version = "=1.10.0" }
paychains-sdk = { path = "../../sdk", version = "=1.10.0" }

[dev-dependencies]
paychains-logger = { path = "../../logger", version = "=1.10.0" }

[lib]
crate-type = ["lib"]
name = "paychains_config_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
