[package]
authors = ["PayChains Maintainers <maintainers@paychains.foundation>"]
edition = "2021"
name = "paychains-net-shaper"
description = "The paychains cluster network shaping tool"
version = "1.10.0"
repository = "https://github.com/paychains-labs/paychains"
license = "Apache-2.0"
homepage = "https://paychains.com/"
publish = false

[dependencies]
clap = "2.33.1"
serde = "1.0.133"
serde_json = "1.0.74"
paychains-logger = { path = "../logger", version = "=1.10.0" }
rand = "0.7.0"

[[bin]]
name = "paychains-net-shaper"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
