[package]
name = "paychains-cargo-build-bpf"
version = "1.10.0"
description = "Compile a local package and all of its dependencies using the PayChains BPF SDK"
authors = ["PayChains Maintainers <maintainers@paychains.foundation>"]
repository = "https://github.com/paychains-labs/paychains"
homepage = "https://paychains.com/"
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
bzip2 = "0.4.3"
clap = "2.33.3"
regex = "1.5.4"
cargo_metadata = "0.14.1"
paychains-sdk = { path = "..", version = "=1.10.0" }
paychains-download-utils = { path = "../../download-utils", version = "=1.10.0" }
tar = "0.4.38"

[dev-dependencies]
serial_test = "*"

[features]
program = []

[[bin]]
name = "cargo-build-bpf"
path = "src/main.rs"
