[package]
authors = ["PayChains Maintainers <maintainers@paychains.com>"]
description = "Blockchain, Rebuilt for Scale"
edition = "2021"
homepage = "https://paychains.com/"
license = "Apache-2.0"
name = "proto"
publish = false
repository = "https://github.com/paychains-labs/paychains"
version = "1.10.0"

[workspace]

[dependencies]
tonic-build = "0.6.0"
