[package]
name = "paychains-bpf-rust-upgradeable"
version = "1.10.0"
description = "PayChains BPF test program written in Rust"
authors = ["PayChains Maintainers <maintainers@paychains.foundation>"]
repository = "https://github.com/paychains-labs/paychains"
license = "Apache-2.0"
homepage = "https://paychains.com/"
documentation = "https://docs.rs/paychains-bpf-rust-upgradeable"
edition = "2021"

[dependencies]
paychains-program = { path = "../../../../sdk/program", version = "=1.10.0" }

[lib]
name = "paychains_bpf_rust_upgradeable"
crate-type = ["cdylib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
