[package]
authors = ["PayChains Maintainers <maintainers@paychains.foundation>"]
edition = "2021"
name = "paychains-replica-node"
description = "PayChains replication node"
version = "1.10.0"
repository = "https://github.com/paychains-labs/paychains"
license = "Apache-2.0"
homepage = "https://paychains.com/"
documentation = "https://docs.rs/paychains-validator"

[dependencies]
clap = "2.33.1"
crossbeam-channel = "0.5"
log = "0.4.14"
rand = "0.7.0"
paychains-clap-utils = { path = "../clap-utils", version = "=1.10.0" }
paychains-download-utils = { path = "../download-utils", version = "=1.10.0" }
paychains-genesis-utils = { path = "../genesis-utils", version = "=1.10.0" }
paychains-gossip = { path = "../gossip", version = "=1.10.0" }
paychains-ledger = { path = "../ledger", version = "=1.10.0" }
paychains-logger = { path = "../logger", version = "=1.10.0" }
paychains-net-utils = { path = "../net-utils", version = "=1.10.0" }
paychains-rpc = { path = "../rpc", version = "=1.10.0" }
paychains-replica-lib = { path = "../replica-lib", version = "=1.10.0" }
paychains-runtime = { path = "../runtime", version = "=1.10.0" }
paychains-sdk = { path = "../sdk", version = "=1.10.0" }
paychains-send-transaction-service = { path = "../send-transaction-service", version = "=1.10.0" }
paychains-streamer = { path = "../streamer", version = "=1.10.0" }
paychains-version = { path = "../version", version = "=1.10.0" }
paychains-validator = { path = "../validator", version = "=1.10.0" }

[dev-dependencies]
serial_test = "0.5.1"
paychains-core = { path = "../core", version = "=1.10.0" }
paychains-local-cluster = { path = "../local-cluster", version = "=1.10.0" }
tempfile = "3.3.0"


[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
tonic-build = "0.6.2"
