[package]
name = "paychains-bpf-loader-program"
version = "1.10.0"
description = "PayChains BPF loader"
authors = ["PayChains Maintainers <maintainers@paychains.foundation>"]
repository = "https://github.com/paychains-labs/paychains"
license = "Apache-2.0"
homepage = "https://paychains.com/"
documentation = "https://docs.rs/paychains-bpf-loader-program"
edition = "2021"

[dependencies]
bincode = "1.3.3"
byteorder = "1.4.3"
log = "0.4.14"
libsecp256k1 = "0.6.0"
paychains-measure = { path = "../../measure", version = "=1.10.0" }
paychains-metrics = { path = "../../metrics", version = "=1.10.0" }
paychains-program-runtime = { path = "../../program-runtime", version = "=1.10.0" }
paychains-sdk = { path = "../../sdk", version = "=1.10.0" }
paychains-zk-token-sdk = { path = "../../zk-token-sdk", version = "=1.10.0" }
paychains_rbpf = "=0.2.21"
thiserror = "1.0"

[dev-dependencies]
rand = "0.7.3"
paychains-runtime = { path = "../../runtime", version = "=1.10.0" }

[lib]
crate-type = ["lib"]
name = "paychains_bpf_loader_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
