[package]
name = "paychains-version"
version = "1.10.0"
description = "PayChains Version"
authors = ["PayChains Maintainers <maintainers@paychains.foundation>"]
repository = "https://github.com/paychains-labs/paychains"
license = "Apache-2.0"
homepage = "https://paychains.com/"
documentation = "https://docs.rs/paychains-version"
edition = "2021"

[dependencies]
log = "0.4.14"
serde = "1.0.133"
serde_derive = "1.0.103"
paychains-frozen-abi = { path = "../frozen-abi", version = "=1.10.0" }
paychains-frozen-abi-macro = { path = "../frozen-abi/macro", version = "=1.10.0" }
paychains-sdk = { path = "../sdk", version = "=1.10.0" }

[lib]
name = "paychains_version"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
rustc_version = "0.4"
