[package]
name = "paychains-bpf-rust-param-passing-dep"
version = "1.10.0"
description = "PayChains BPF program written in Rust"
authors = ["PayChains Maintainers <maintainers@paychains.foundation>"]
repository = "https://github.com/paychains-labs/paychains"
license = "Apache-2.0"
homepage = "https://paychains.com/"
documentation = "https://docs.rs/paychains-bpf-rust-param-passing-dep"
edition = "2021"

[dependencies]
paychains-program = { path = "../../../../sdk/program", version = "=1.10.0" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
