[package]
authors = ["PayChains Maintainers <maintainers@paychains.foundation>"]
edition = "2021"
name = "paychains-validator"
description = "Blockchain, Rebuilt for Scale"
version = "1.10.0"
repository = "https://github.com/paychains-labs/paychains"
license = "Apache-2.0"
homepage = "https://paychains.com/"
documentation = "https://docs.rs/paychains-validator"
default-run = "paychains-validator"

[dependencies]
chrono = { version = "0.4.11", features = ["serde"] }
clap = "2.33.1"
console = "0.15.0"
core_affinity = "0.5.10"
crossbeam-channel = "0.5"
fd-lock = "3.0.2"
indicatif = "0.16.2"
jsonrpc-core = "18.0.0"
jsonrpc-core-client = { version = "18.0.0", features = ["ipc", "ws"] }
jsonrpc-derive = "18.0.0"
jsonrpc-ipc-server = "18.0.0"
jsonrpc-server-utils= "18.0.0"
log = "0.4.14"
num_cpus = "1.13.1"
rand = "0.7.0"
serde = "1.0.133"
serde_json = "1.0.74"
paychains-clap-utils = { path = "../clap-utils", version = "=1.10.0" }
paychains-cli-config = { path = "../cli-config", version = "=1.10.0" }
paychains-client = { path = "../client", version = "=1.10.0" }
paychains-core = { path = "../core", version = "=1.10.0" }
paychains-download-utils = { path = "../download-utils", version = "=1.10.0" }
paychains-entry = { path = "../entry", version = "=1.10.0" }
paychains-faucet = { path = "../faucet", version = "=1.10.0" }
paychains-genesis-utils = { path = "../genesis-utils", version = "=1.10.0" }
paychains-gossip = { path = "../gossip", version = "=1.10.0" }
paychains-ledger = { path = "../ledger", version = "=1.10.0" }
paychains-logger = { path = "../logger", version = "=1.10.0" }
paychains-metrics = { path = "../metrics", version = "=1.10.0" }
paychains-net-utils = { path = "../net-utils", version = "=1.10.0" }
paychains-perf = { path = "../perf", version = "=1.10.0" }
paychains-poh = { path = "../poh", version = "=1.10.0" }
paychains-replica-lib = { path = "../replica-lib", version = "=1.10.0" }
paychains-rpc = { path = "../rpc", version = "=1.10.0" }
paychains-runtime = { path = "../runtime", version = "=1.10.0" }
paychains-sdk = { path = "../sdk", version = "=1.10.0" }
paychains-send-transaction-service = { path = "../send-transaction-service", version = "=1.10.0" }
paychains-streamer = { path = "../streamer", version = "=1.10.0" }
paychains-test-validator = { path = "../test-validator", version = "=1.10.0" }
paychains-version = { path = "../version", version = "=1.10.0" }
paychains-vote-program = { path = "../programs/vote", version = "=1.10.0" }
symlink = "0.1.0"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = {package = "tikv-jemallocator", version = "0.4.1", features = ["unprefixed_malloc_on_supported_platforms"]}

[target."cfg(unix)".dependencies]
libc = "0.2.112"
signal-hook = "0.3.13"
sysctl = "0.4.3"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
