[package]
name = "paychains-address-lookup-table-program"
version = "1.10.0"
description = "PayChains address lookup table program"
authors = ["PayChains Maintainers <maintainers@paychains.foundation>"]
repository = "https://github.com/paychains-labs/paychains"
license = "Apache-2.0"
homepage = "https://paychains.com/"
documentation = "https://docs.rs/paychains-address-loookup-table-program"
edition = "2021"

[dependencies]
bincode = "1.3.3"
bytemuck = "1.7.3"
log = "0.4.14"
num-derive = "0.3"
num-traits = "0.2"
serde = { version = "1.0.133", features = ["derive"] }
paychains-frozen-abi = { path = "../../frozen-abi", version = "=1.10.0" }
paychains-frozen-abi-macro = { path = "../../frozen-abi/macro", version = "=1.10.0" }
paychains-program-runtime = { path = "../../program-runtime", version = "=1.10.0" }
paychains-sdk = { path = "../../sdk", version = "=1.10.0" }
thiserror = "1.0"

[build-dependencies]
rustc_version = "0.4"

[lib]
crate-type = ["lib"]
name = "paychains_address_lookup_table_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
