[package]
name = "paychains-bpf-rust-rand"
version = "1.10.0"
description = "PayChains BPF test program written in Rust"
authors = ["PayChains Maintainers <maintainers@paychains.foundation>"]
repository = "https://github.com/paychains-labs/paychains"
license = "Apache-2.0"
homepage = "https://paychains.com/"
documentation = "https://docs.rs/paychains-bpf-rust-rand"
edition = "2021"

[dependencies]
getrandom = { version = "0.1.14", features = ["dummy"] }
rand = "0.7"
paychains-program = { path = "../../../../sdk/program", version = "=1.10.0" }

[lib]
crate-type = ["cdylib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
