[package]
name = "paychains-compute-budget-program"
description = "PayChains Compute Budget program"
version = "1.10.0"
homepage = "https://paychains.com/"
documentation = "https://docs.rs/paychains-compute-budget-program"
repository = "https://github.com/paychains-labs/paychains"
authors = ["PayChains Maintainers <maintainers@paychains.foundation>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
paychains-program-runtime = { path = "../../program-runtime", version = "=1.10.0" }
paychains-sdk = { path = "../../sdk", version = "=1.10.0" }

[lib]
crate-type = ["lib"]
name = "paychains_compute_budget_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
