[package]
name = "paychains-streamer"
version = "1.10.0"
description = "PayChains Streamer"
authors = ["PayChains Maintainers <maintainers@paychains.foundation>"]
repository = "https://github.com/paychains-labs/paychains"
license = "Apache-2.0"
homepage = "https://paychains.com/"
documentation = "https://docs.rs/paychains-streamer"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5"
histogram = "0.6.9"
itertools = "0.10.3"
log = "0.4.14"
paychains-metrics = { path = "../metrics", version = "=1.10.0" }
paychains-sdk = { path = "../sdk", version = "=1.10.0" }
thiserror = "1.0"
libc = "0.2.112"
nix = "0.23.1"
paychains-perf = { path = "../perf", version = "=1.10.0" }

[dev-dependencies]
paychains-logger = { path = "../logger", version = "=1.10.0" }

[lib]
crate-type = ["lib"]
name = "paychains_streamer"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
