[package]
name = "paychains-program-runtime"
version = "1.10.0"
description = "PayChains program runtime"
authors = ["PayChains Maintainers <maintainers@paychains.foundation>"]
repository = "https://github.com/paychains-labs/paychains"
license = "Apache-2.0"
homepage = "https://paychains.com/"
documentation = "https://docs.rs/paychains-program-runtime"
edition = "2021"

[dependencies]
base64 = "0.13"
bincode = "1.3.3"
itertools =  "0.10.1"
libc = "0.2.101"
libloading = "0.7.0"
log = "0.4.14"
num-derive = { version = "0.3" }
num-traits = { version = "0.2" }
serde = { version = "1.0.129", features = ["derive", "rc"] }
paychains-frozen-abi = { path = "../frozen-abi", version = "=1.10.0" }
paychains-frozen-abi-macro = { path = "../frozen-abi/macro", version = "=1.10.0" }
paychains-measure = { path = "../measure", version = "=1.10.0" }
paychains-sdk = { path = "../sdk", version = "=1.10.0" }
thiserror = "1.0"

[dev-dependencies]
paychains-logger = { path = "../logger", version = "=1.10.0" }

[lib]
crate-type = ["lib"]
name = "paychains_program_runtime"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
rustc_version = "0.4"
