[package]
name = "paychains-stake-accounts"
description = "Blockchain, Rebuilt for Scale"
authors = ["PayChains Maintainers <maintainers@paychains.foundation>"]
edition = "2021"
version = "1.10.0"
repository = "https://github.com/paychains-labs/paychains"
license = "Apache-2.0"
homepage = "https://paychains.com/"
documentation = "https://docs.rs/paychains-stake-accounts"

[dependencies]
clap = "2.33.1"
paychains-clap-utils = { path = "../clap-utils", version = "=1.10.0" }
paychains-cli-config = { path = "../cli-config", version = "=1.10.0" }
paychains-client = { path = "../client", version = "=1.10.0" }
paychains-remote-wallet = { path = "../remote-wallet", version = "=1.10.0" }
paychains-sdk = { path = "../sdk", version = "=1.10.0" }
paychains-stake-program = { path = "../programs/stake", version = "=1.10.0" }

[dev-dependencies]
paychains-runtime = { path = "../runtime", version = "=1.10.0" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
