[package]
name = "paychains-zk-token-proof-program"
description = "PayChains Zk Token Proof Program"
authors = ["PayChains Maintainers <maintainers@paychains.foundation>"]
repository = "https://github.com/paychains-labs/paychains"
version = "1.10.0"
license = "Apache-2.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.7.2", features = ["derive"] }
getrandom = { version = "0.1", features = ["dummy"] }
num-derive = "0.3"
num-traits = "0.2"
paychains-program-runtime = { path = "../../program-runtime", version = "=1.10.0" }
paychains-sdk = { path = "../../sdk", version = "=1.10.0" }
paychains-zk-token-sdk = { path = "../../zk-token-sdk", version = "=1.10.0" }
