[package]
name = "paychains-tokens"
description = "Blockchain, Rebuilt for Scale"
authors = ["PayChains Maintainers <maintainers@paychains.foundation>"]
edition = "2021"
version = "1.10.0"
repository = "https://github.com/paychains-labs/paychains"
license = "Apache-2.0"
homepage = "https://paychains.com/"
documentation = "https://docs.rs/paychains-tokens"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = "2.33.0"
console = "0.15.0"
csv = "1.1.6"
ctrlc = { version = "3.2.1", features = ["termination"] }
indexmap = "1.8.0"
indicatif = "0.16.2"
pickledb = "0.4.1"
serde = { version = "1.0", features = ["derive"] }
paychains-account-decoder = { path = "../account-decoder", version = "=1.10.0" }
paychains-clap-utils = { path = "../clap-utils", version = "=1.10.0" }
paychains-cli-config = { path = "../cli-config", version = "=1.10.0" }
paychains-client = { path = "../client", version = "=1.10.0" }
paychains-remote-wallet = { path = "../remote-wallet", version = "=1.10.0" }
paychains-sdk = { path = "../sdk", version = "=1.10.0" }
paychains-transaction-status = { path = "../transaction-status", version = "=1.10.0" }
paychains-version = { path = "../version", version = "=1.10.0" }
spl-associated-token-account = { version = "=1.0.3" }
spl-token = { version = "=3.2.0", features = ["no-entrypoint"] }
tempfile = "3.3.0"
thiserror = "1.0"

[dev-dependencies]
bincode = "1.3.3"
paychains-logger = { path = "../logger", version = "=1.10.0" }
paychains-streamer = { path = "../streamer", version = "=1.10.0" }
paychains-test-validator = { path = "../test-validator", version = "=1.10.0" }
