[package]
name = "paychains-storage-proto"
version = "1.10.0"
description = "PayChains Storage Protobuf Definitions"
authors = ["PayChains Maintainers <maintainers@paychains.com>"]
repository = "https://github.com/paychains-labs/paychains"
license = "Apache-2.0"
homepage = "https://paychains.com/"
documentation = "https://docs.rs/paychains-storage-proto"
edition = "2021"

[dependencies]
bincode = "1.3.3"
bs58 = "0.4.0"
prost = "0.9.0"
serde = "1.0.133"
paychains-account-decoder = { path = "../account-decoder", version = "=1.10.0" }
paychains-sdk = { path = "../sdk", version = "=1.10.0" }
paychains-transaction-status = { path = "../transaction-status", version = "=1.10.0" }

[dev-dependencies]
enum-iterator = "0.7.0"

[lib]
crate-type = ["lib"]
name = "paychains_storage_proto"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
tonic-build = "0.6.2"
