[package]
name = "paychains-rayon-threadlimit"
version = "1.10.0"
description = "paychains-rayon-threadlimit"
homepage = "https://paychains.com/"
documentation = "https://docs.rs/paychains-rayon-threadlimit"
readme = "../README.md"
repository = "https://github.com/paychains-labs/paychains"
authors = ["PayChains Maintainers <maintainers@paychains.foundation>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
num_cpus = "1.13.1"
lazy_static = "1.4.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
