[package]
name = "paychains-frozen-abi-macro"
version = "1.10.0"
description = "PayChains Frozen ABI Macro"
authors = ["PayChains Maintainers <maintainers@paychains.foundation>"]
repository = "https://github.com/paychains-labs/paychains"
homepage = "https://paychains.com/"
documentation = "https://docs.rs/paychains-frozen-abi-macro"
license = "Apache-2.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full", "extra-traits"] }

[build-dependencies]
rustc_version = "0.4"
