[package]
name = "paychains-bpf-rust-invoke"
version = "1.10.0"
description = "PayChains BPF test program written in Rust"
authors = ["PayChains Maintainers <maintainers@paychains.foundation>"]
repository = "https://github.com/paychains-labs/paychains"
license = "Apache-2.0"
homepage = "https://paychains.com/"
documentation = "https://docs.rs/paychains-bpf-rust-invoke"
edition = "2021"

[features]
default = ["program"]
program = []

[dependencies]
paychains-bpf-rust-invoked = { path = "../invoked", default-features = false }
paychains-program = { path = "../../../../sdk/program", version = "=1.10.0" }

[lib]
crate-type = ["lib", "cdylib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
