# This package only exists to avoid circular dependencies during cargo publish:
# paychains-runtime -> paychains-address-program-runtime -> paychains-program-test -> paychains-runtime

[package]
name = "paychains-address-lookup-table-program-tests"
version = "1.10.0"
authors = ["PayChains Maintainers <maintainers@paychains.foundation>"]
repository = "https://github.com/paychains-labs/paychains"
license = "Apache-2.0"
homepage = "https://paychains.com/"
edition = "2021"
publish = false

[dev-dependencies]
assert_matches = "1.5.0"
bincode = "1.3.3"
paychains-address-lookup-table-program = { path = "../address-lookup-table", version = "=1.10.0" }
paychains-program-test = { path = "../../program-test", version = "=1.10.0" }
paychains-sdk = { path = "../../sdk", version = "=1.10.0" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
