[package]
name = "paychains-test-validator"
description = "Blockchain, Rebuilt for Scale"
version = "1.10.0"
homepage = "https://paychains.com/"
documentation = "https://docs.rs/paychains-test-validator"
readme = "../README.md"
repository = "https://github.com/paychains-labs/paychains"
authors = ["PayChains Maintainers <maintainers@paychains.foundation>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
base64 = "0.12.3"
log = "0.4.14"
serde_derive = "1.0.103"
serde_json = "1.0.74"
paychains-cli-output = { path = "../cli-output", version = "=1.10.0" }
paychains-client = { path = "../client", version = "=1.10.0" }
paychains-core = { path = "../core", version = "=1.10.0" }
paychains-gossip = { path = "../gossip", version = "=1.10.0" }
paychains-ledger = { path = "../ledger", version = "=1.10.0" }
paychains-logger = { path = "../logger", version = "=1.10.0" }
paychains-net-utils = { path = "../net-utils", version = "=1.10.0" }
paychains-program-test = { path = "../program-test", version = "=1.10.0" }
paychains-rpc = { path = "../rpc", version = "=1.10.0" }
paychains-runtime = { path = "../runtime", version = "=1.10.0" }
paychains-sdk = { path = "../sdk", version = "=1.10.0" }
paychains-streamer = { path = "../streamer", version = "=1.10.0" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
