[package]
name = "paychains-net-utils"
version = "1.10.0"
description = "PayChains Network Utilities"
authors = ["PayChains Maintainers <maintainers@paychains.foundation>"]
repository = "https://github.com/paychains-labs/paychains"
license = "Apache-2.0"
homepage = "https://paychains.com/"
documentation = "https://docs.rs/paychains-net-utils"
edition = "2021"

[dependencies]
bincode = "1.3.3"
clap = "2.33.1"
crossbeam-channel = "0.5"
log = "0.4.14"
nix = "0.23.1"
rand = "0.7.0"
serde = "1.0.133"
serde_derive = "1.0.103"
socket2 = "0.4.2"
paychains-logger = { path = "../logger", version = "=1.10.0" }
paychains-sdk = { path = "../sdk", version = "=1.10.0" }
paychains-version = { path = "../version", version = "=1.10.0" }
tokio = { version = "1", features = ["full"] }
url = "2.2.2"

[lib]
name = "paychains_net_utils"

[[bin]]
name = "paychains-ip-address"
path = "src/bin/ip_address.rs"

[[bin]]
name = "paychains-ip-address-server"
path = "src/bin/ip_address_server.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
