[package]
authors = ["PayChains Maintainers <maintainers@paychains.foundation>"]
description = "PayChains Program Test Framework"
edition = "2021"
license = "Apache-2.0"
name = "paychains-program-test"
repository = "https://github.com/paychains-labs/paychains"
version = "1.10.0"

[dependencies]
async-trait = "0.1.52"
base64 = "0.12.3"
bincode = "1.3.3"
chrono-humanize = "0.2.1"
log = "0.4.14"
serde = "1.0.133"
paychains-banks-client = { path = "../banks-client", version = "=1.10.0" }
paychains-banks-server = { path = "../banks-server", version = "=1.10.0" }
paychains-bpf-loader-program = { path = "../programs/bpf_loader", version = "=1.10.0" }
paychains-logger = { path = "../logger", version = "=1.10.0" }
paychains-program-runtime = { path = "../program-runtime", version = "=1.10.0" }
paychains-runtime = { path = "../runtime", version = "=1.10.0" }
paychains-sdk = { path = "../sdk", version = "=1.10.0" }
paychains-vote-program = { path = "../programs/vote", version = "=1.10.0" }
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
