[package]
name = "paychains-upload-perf"
version = "1.10.0"
description = "Metrics Upload Utility"
authors = ["PayChains Maintainers <maintainers@paychains.foundation>"]
repository = "https://github.com/paychains-labs/paychains"
license = "Apache-2.0"
edition = "2021"
homepage = "https://paychains.com/"
publish = false

[dependencies]
serde_json = "1.0.74"
paychains-metrics = { path = "../metrics", version = "=1.10.0" }

[[bin]]
name = "paychains-upload-perf"
path = "src/upload-perf.rs"


[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
