[package]
name = "paychains-send-transaction-service"
version = "1.10.0"
description = "PayChains send transaction service"
authors = ["PayChains Maintainers <maintainers@paychains.foundation>"]
repository = "https://github.com/paychains-labs/paychains"
homepage = "https://paychains.com/"
documentation = "https://docs.rs/paychains-send-transaction-service"
license = "Apache-2.0"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5"
log = "0.4.14"
paychains-metrics = { path = "../metrics", version = "=1.10.0" }
paychains-runtime = { path = "../runtime", version = "=1.10.0" }
paychains-sdk = { path = "../sdk", version = "=1.10.0" }

[dev-dependencies]
paychains-logger = { path = "../logger", version = "=1.10.0" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
