[package]
authors = ["PayChains Maintainers <maintainers@paychains.foundation>"]
edition = "2021"
name = "paychains-store-tool"
description = "Tool to inspect append vecs"
version = "1.10.0"
repository = "https://github.com/paychains-labs/paychains"
license = "Apache-2.0"
homepage = "https://paychains.com/"
publish = false

[dependencies]
log = { version = "0.4.14" }
paychains-logger = { path = "../../logger", version = "=1.10.0" }
paychains-version = { path = "../../version", version = "=1.10.0" }
paychains-runtime = { path = "..", version = "=1.10.0" }
clap = "2.33.1"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
