[package]
name = "paychains-poh"
version = "1.10.0"
description = "PayChains PoH"
authors = ["PayChains Maintainers <maintainers@paychains.foundation>"]
repository = "https://github.com/paychains-labs/paychains"
license = "Apache-2.0"
homepage = "https://paychains.com/"
documentation = "https://docs.rs/paychains-poh"
edition = "2021"

[dependencies]
core_affinity = "0.5.10"
crossbeam-channel = "0.5"
log = "0.4.14"
paychains-entry = { path = "../entry", version = "=1.10.0" }
paychains-ledger = { path = "../ledger", version = "=1.10.0" }
paychains-measure = { path = "../measure", version = "=1.10.0" }
paychains-metrics = { path = "../metrics", version = "=1.10.0" }
paychains-runtime = { path = "../runtime", version = "=1.10.0" }
paychains-sdk = { path = "../sdk", version = "=1.10.0" }
paychains-sys-tuner = { path = "../sys-tuner", version = "=1.10.0" }
thiserror = "1.0"

[dev-dependencies]
bincode = "1.3.3"
matches = "0.1.9"
rand = "0.7.0"
paychains-logger = { path = "../logger", version = "=1.10.0" }
paychains-perf = { path = "../perf", version = "=1.10.0" }

[lib]
crate-type = ["lib"]
name = "paychains_poh"

[[bench]]
name = "poh"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
