[package]
name = "paychains-metrics"
version = "1.10.0"
description = "PayChains Metrics"
authors = ["PayChains Maintainers <maintainers@paychains.foundation>"]
repository = "https://github.com/paychains-labs/paychains"
license = "Apache-2.0"
homepage = "https://paychains.com/"
documentation = "https://docs.rs/paychains-metrics"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5"
gethostname = "0.2.1"
lazy_static = "1.4.0"
log = "0.4.14"
reqwest = { version = "0.11.6", default-features = false, features = ["blocking", "rustls-tls", "json"] }
paychains-sdk = { path = "../sdk", version = "=1.10.0" }

[dev-dependencies]
env_logger = "0.9.0"
rand = "0.7.0"
serial_test = "0.5.1"

[lib]
name = "paychains_metrics"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
